---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-uri: 'https://github.com/JurajBrabec/loadbalancing-test.git'
  labels:
    app: app-2
    app.kubernetes.io/part-of: loadbalancing-test
  name: app-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-2
      app.kubernetes.io/part-of: loadbalancing-test
      deployment: app-2
  template:
    metadata:
      labels:
        app: app-2
        app.kubernetes.io/part-of: loadbalancing-test
        deployment: app-2
    spec:
      containers:
        - command:
            [
              'sh',
              '-c',
              'cd /opt/code-base && npm install && npm run dev:app-2',
            ]
          env:
            - name: DEV_MODE
              value: 'true'
          image: registry.access.redhat.com/ubi8/nodejs-20
          name: app-2
          volumeMounts:
            - name: code-base
              mountPath: /opt/code-base
              subPath: loadbalancing-test
      volumes:
        - name: code-base
          persistentVolumeClaim:
            claimName: code-base
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-2
    app.kubernetes.io/part-of: loadbalancing-test
  name: app-2-debugger
spec:
  ports:
    - name: 5858-tcp
      protocol: TCP
      port: 5858
      targetPort: 5858
  selector:
    app: app-2
    app.kubernetes.io/part-of: loadbalancing-test
    deployment: app-2
