---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-uri: 'https://github.com/JurajBrabec/loadbalancing-test.git'
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"dev-image:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"dev-image\")].image"}]'
  name: dev-image
  labels:
    app: dev-image
    app.kubernetes.io/part-of: loadbalancing-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-image
      app.kubernetes.io/part-of: loadbalancing-test
      deployment: dev-image
  template:
    metadata:
      labels:
        app: dev-image
        app.kubernetes.io/part-of: loadbalancing-test
        deployment: dev-image
    spec:
      # initContainers:
      #   - name: init-permissions
      #     image: busybox
      #     command:
      #       [
      #         'sh',
      #         '-c',
      #         'chmod -R 777 /mnt/code-base && chown -R nobody:nogroup /mnt/code-base',
      #       ]
      #     resources:
      #       limits:
      #         cpu: 100m
      #         memory: 128Mi
      # volumeMounts:
      #   - mountPath: /mnt/code-base
      #     name: code-base
      containers:
        - image: ' '
          imagePullPolicy: Always
          name: dev-image
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: code-base
              mountPath: /opt/code-base
      # securityContext:
      #   allowPrivilegeEscalation: false
      #   capabilities:
      #     drop:
      #       - ALL
      #   runAsUser: 1000000000
      #   fsGroup: 1000000000
      volumes:
        - name: code-base
          persistentVolumeClaim:
            claimName: code-base
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - dev-image
        from:
          kind: ImageStreamTag
          name: 'dev-image:latest'
    - type: ConfigChange
