---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-base
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  volumeName: code-base
