---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: 'envoy'
    app.openshift.io/vcs-uri: 'https://github.com/JurajBrabec/loadbalancing-test.git'
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"app-1:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"app-1\")].image"}]'
  labels:
    app: app-1
    app.kubernetes.io/part-of: loadbalancing-test
  name: app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1
      app.kubernetes.io/part-of: loadbalancing-test
      deployment: app-1
  template:
    metadata:
      labels:
        app: app-1
        app.kubernetes.io/part-of: loadbalancing-test
        deployment: app-1
    spec:
      containers:
        - env:
            - name: APP_2_ADDR
              value: 'app-2:8080'
          image: ' '
          imagePullPolicy: Always
          name: app-1
          ports:
            - containerPort: 8000
              protocol: TCP
