---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: 'core'
    app.openshift.io/vcs-uri: 'https://github.com/excalibur-enterprise/excalibur-v4-api'
  labels:
    app: api
    app.kubernetes.io/part-of: excalibur-v4-dev
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      app.kubernetes.io/part-of: excalibur-v4-dev
      deployment: api
  template:
    metadata:
      labels:
        app: api
        app.kubernetes.io/part-of: excalibur-v4-dev
        deployment: api
    spec:
      containers:
        - command:
            ['sh', '-c', 'cd /opt/excalibur/api && npm install && npm run dev']
          env:
            - name: EXC_API_LOG_CONSOLE_ENABLED
              value: 'true'
            - name: EXC_API_LOG_CONSOLE_LEVEL
              value: 'debug'
            - name: EXC_API_LOG_LOKI_ENABLED
              value: 'false'
            - name: DEV_MODE
              value: 'true'
          image: registry.access.redhat.com/ubi8/nodejs-20
          name: api
          ports:
            - containerPort: 8000
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: '512Mi'
          volumeMounts:
            - name: code-base
              mountPath: /opt/excalibur/api
              subPath: lbt1
            - name: code-base
              mountPath: /var/excalibur/pam/recordings
              subPath: volumes/pam-recordings
      volumes:
        - name: code-base
          persistentVolumeClaim:
            claimName: code-base
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
    app.kubernetes.io/part-of: excalibur-v4-dev
  name: api-debugger
spec:
  ports:
    - name: 5858-tcp
      protocol: TCP
      port: 5858
      targetPort: 5858
  selector:
    app: api
    app.kubernetes.io/part-of: excalibur-v4-dev
    deployment: api
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
    app.kubernetes.io/part-of: excalibur-v4-dev
  name: api-http
spec:
  ports:
    - name: tcp8000
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: api
    app.kubernetes.io/part-of: excalibur-v4-dev
    deployment: api
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
    app.kubernetes.io/part-of: excalibur-v4-dev
  name: api-rpc
spec:
  ports:
    - name: tcp-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: api
    app.kubernetes.io/part-of: excalibur-v4-dev
    deployment: api
