---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: '["cache","core","database","hsm","identity-store","loki","mailer","pam","repository"]'
    app.openshift.io/vcs-uri: 'https://github.com/excalibur-enterprise/excalibur-v4-api'
  labels:
    app: api
    app.kubernetes.io/part-of: excalibur-v4-dev
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      app.kubernetes.io/part-of: excalibur-v4-dev
      deployment: api
  template:
    metadata:
      labels:
        app: api
        app.kubernetes.io/part-of: excalibur-v4-dev
        deployment: api
    spec:
      containers:
        - command: ['sh', '-c', 'cd /opt/excalibur/api; npm run dev']
          env:
            - name: DEV_MODE
              value: 'true'
            - name: EXC_API_LOG_CONSOLE_ENABLED
              value: 'true'
            - name: EXC_API_LOG_CONSOLE_LEVEL
              value: 'debug'
            - name: EXC_API_LOG_LOKI_ENABLED
              value: 'false'
          #          image: registry.access.redhat.com/ubi8/nodejs-20
          image: ghcr.io/excalibur-enterprise/api:latest
          name: api
          ports:
            - containerPort: 5858
              protocol: TCP
            - containerPort: 8000
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: '1'
              memory: 2Gi
          volumeMounts:
            - name: code-base
              mountPath: /opt/excalibur/api
              subPath: excalibur-v4/services/api
            - name: code-base
              mountPath: /var/excalibur/pam/recordings
              subPath: volumes/pam-recordings
      imagePullSecrets:
        - name: ghcr-auth
      volumes:
        - name: code-base
          persistentVolumeClaim:
            claimName: code-base
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
    app.kubernetes.io/part-of: excalibur-v4-dev
  name: api
spec:
  ports:
    - name: node-inspector
      protocol: TCP
      port: 5858
      targetPort: 5858
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: grpc
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: api
    app.kubernetes.io/part-of: excalibur-v4-dev
    deployment: api
