apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    dir /tmp
    save ""
    appendonly no
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: 'core'
    app.openshift.io/vcs-uri: 'https://github.com/excalibur-enterprise/excalibur-v4'
  labels:
    app: cache
    app.kubernetes.io/part-of: excalibur-v4-dev
  name: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
      app.kubernetes.io/part-of: excalibur-v4-dev
      deployment: cache
  template:
    metadata:
      labels:
        app: cache
        app.kubernetes.io/part-of: excalibur-v4-dev
        deployment: cache
    spec:
      containers:
        - image: redis:7.2.0-alpine
          name: cache
          ports:
            - containerPort: 6379
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 1
              memory: 512Mi
          volumeMounts:
            - mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
              name: redis-config
          command: ['redis-server', '/usr/local/etc/redis/redis.conf']
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cache
    app.kubernetes.io/part-of: excalibur-v4-dev
  name: cache
spec:
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: cache
    app.kubernetes.io/part-of: excalibur-v4-dev
    deployment: cache
