---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: '["core","repository","loki"]'
    app.openshift.io/vcs-uri: 'https://github.com/excalibur-enterprise/excalibur-v4-api'
  labels:
    app: client
    app.kubernetes.io/part-of: excalibur-v4-dev
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
      app.kubernetes.io/part-of: excalibur-v4-dev
      deployment: client
  template:
    metadata:
      labels:
        app: client
        app.kubernetes.io/part-of: excalibur-v4-dev
        deployment: client
    spec:
      containers:
        - command: ['sh', '-c', 'cd /opt/excalibur/client; npm run dev']
          env:
            - name: DEV_MODE
              value: 'true'
            - name: EXC_CLIENT_LOG_CONSOLE_ENABLED
              value: 'true'
            - name: EXC_CLIENT_LOG_CONSOLE_LEVEL
              value: debug
            - name: EXC_CLIENT_LOG_LOKI_ENABLED
              value: 'false'
          # image: registry.access.redhat.com/ubi8/nodejs-20
          image: ghcr.io/excalibur-enterprise/devel
          name: client
          ports:
            - containerPort: 5858
              protocol: TCP
            - containerPort: 8000
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8000
            timeoutSeconds: 1
            initialDelaySeconds: 30
          resources:
            requests:
              cpu: 1m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: code-base
              mountPath: /opt/excalibur/client
              subPath: excalibur-v4/services/client
      imagePullSecrets:
        - name: ghcr-auth
      volumes:
        - name: code-base
          persistentVolumeClaim:
            claimName: code-base
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: client
    app.kubernetes.io/part-of: excalibur-v4-dev
  name: client
spec:
  ports:
    - name: node-inspector
      protocol: TCP
      port: 5858
      targetPort: 5858
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: grpc
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: client
    app.kubernetes.io/part-of: excalibur-v4-dev
    deployment: client
