---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: '["ca","cache","hsm","identity-store","loki","mailer","pam","repository"]'
    app.openshift.io/vcs-uri: 'https://github.com/excalibur-enterprise/excalibur-v4-api'
  labels:
    app: core
    app.kubernetes.io/part-of: excalibur-v4-dev
  name: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
      app.kubernetes.io/part-of: excalibur-v4-dev
      deployment: core
  template:
    metadata:
      labels:
        app: core
        app.kubernetes.io/part-of: excalibur-v4-dev
        deployment: core
    spec:
      containers:
        - command: ['sh', '-c', 'cd /opt/excalibur/core; npm run dev']
          env:
            - name: DEV_MODE
              value: 'true'
            - name: EXC_CORE_LOG_CONSOLE_ENABLED
              value: 'true'
            - name: EXC_CORE_LOG_CONSOLE_LEVEL
              value: debug
            - name: EXC_CORE_LOKI_ENABLED
              value: 'false'
            - name: EXC_CORE_CA_URL
              value: https://ca.xclbr.dev
            - name: NODE_EXTRA_CA_CERTS
              value: /usr/local/share/ca-certificates/ca.xclbr.dev.crt
          # image: registry.access.redhat.com/ubi8/nodejs-20
          image: ghcr.io/excalibur-enterprise/core:4.0.0-alpha.2
          name: core
          ports:
            - containerPort: 5858
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
            initialDelaySeconds: 30
          resources:
            requests:
              cpu: 1m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: code-base
              mountPath: /opt/excalibur/core
              subPath: excalibur-v4/services/core
            - name: code-base
              mountPath: /usr/local/share/ca-certificates/ca.xclbr.dev.crt
              subPath: excalibur-v4/deploy/certificates/ca.xclbr.dev.crt
      imagePullSecrets:
        - name: ghcr-auth
      volumes:
        - name: code-base
          persistentVolumeClaim:
            claimName: code-base
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: core
    app.kubernetes.io/part-of: excalibur-v4-dev
  name: core
spec:
  ports:
    - name: node-inspector
      protocol: TCP
      port: 5858
      targetPort: 5858
    - name: grpc
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: core
    app.kubernetes.io/part-of: excalibur-v4-dev
    deployment: core
