---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: '["loki"]'
    app.openshift.io/vcs-uri: 'https://github.com/excalibur-enterprise/excalibur-v4-api'
  labels:
    app: grafana
    app.kubernetes.io/part-of: excalibur-v4-dev
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      app.kubernetes.io/part-of: excalibur-v4-dev
      deployment: grafana
  template:
    metadata:
      labels:
        app: grafana
        app.kubernetes.io/part-of: excalibur-v4-dev
        deployment: grafana
    spec:
      containers:
        - env:
            - name: EXC_SERVER_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: environment-variables
                  key: EXC_SERVER_HOSTNAME
            - name: GF_SERVER_ROOT_URL
              value: 'http://$(EXC_SERVER_HOSTNAME)/admin'
            - name: GF_SERVER_FROM_SUB_PATH
              value: 'true'
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                configMapKeyRef:
                  name: environment-variables
                  key: EXC_ADMIN_USER
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-admin
                  key: password
          image: grafana/grafana:10.0.2
          name: grafana
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 1m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: code-base
              mountPath: /etc/grafana/provisioning/datasources
              subPath: excalibur-v4/services/grafana/provisioning/datasources
            - name: code-base
              mountPath: /var/lib/grafana
              subPath: volumes/grafana-data
      volumes:
        - name: code-base
          persistentVolumeClaim:
            claimName: code-base
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
    app.kubernetes.io/part-of: excalibur-v4-dev
  name: grafana
spec:
  ports:
    - name: tcp-3000
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: grafana
    app.kubernetes.io/part-of: excalibur-v4-dev
    deployment: grafana
