---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: '["ca","cache","loki","mailer","pam","repository"]'
    app.openshift.io/vcs-uri: 'https://github.com/excalibur-enterprise/excalibur-v4-api'
  labels:
    app: identity-store
    app.kubernetes.io/part-of: excalibur-v4-dev
  name: identity-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-store
      app.kubernetes.io/part-of: excalibur-v4-dev
      deployment: identity-store
  template:
    metadata:
      labels:
        app: identity-store
        app.kubernetes.io/part-of: excalibur-v4-dev
        deployment: identity-store
    spec:
      containers:
        - command: ['sh', '-c', 'cd /opt/excalibur/identity-store; npm run dev']
          env:
            - name: DEV_MODE
              value: 'true'
            - name: EXC_IDENTITY_STORE_LOG_CONSOLE_ENABLED
              value: 'true'
            - name: EXC_IDENTITY_STORE_LOG_CONSOLE_LEVEL
              value: debug
            - name: EXC_IDENTITY_STORE_LOG_LOKI_ENABLED
              value: 'false'
          image: registry.access.redhat.com/ubi8/nodejs-20
          name: identity-store
          ports:
            - containerPort: 5858
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 1
              memory: 512Mi
          volumeMounts:
            - name: code-base
              mountPath: /opt/excalibur/identity-store
              subPath: excalibur-v4/services/identity-store
      volumes:
        - name: code-base
          persistentVolumeClaim:
            claimName: code-base
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: identity-store
    app.kubernetes.io/part-of: excalibur-v4-dev
  name: identity-store
spec:
  ports:
    - name: tcp-inspector
      protocol: TCP
      port: 5858
      targetPort: 5858
    - name: tcp-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: identity-store
    app.kubernetes.io/part-of: excalibur-v4-dev
    deployment: identity-store
