---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: '[]'
    app.openshift.io/vcs-uri: 'https://github.com/excalibur-enterprise/excalibur-v4-api'
  labels:
    app: pam-client
    app.kubernetes.io/part-of: excalibur-v4-dev
  name: pam-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pam-client
      app.kubernetes.io/part-of: excalibur-v4-dev
      deployment: pam-client
  template:
    metadata:
      labels:
        app: pam-client
        app.kubernetes.io/part-of: excalibur-v4-dev
        deployment: pam-client
    spec:
      containers:
        - command: ['sh', '-c', 'cd /opt/excalibur/pam-client; npm start']
          env:
            - name: DEV_MODE
              value: 'true'
          image: registry.access.redhat.com/ubi8/nodejs-20
          name: pam-client
          ports:
            - containerPort: 5858
              protocol: TCP
            - containerPort: 3001
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 1
              memory: 2Gi
          volumeMounts:
            - name: code-base
              mountPath: /opt/excalibur/pam-client
              subPath: excalibur-v4/services/pam-client
            - name: code-base
              mountPath: /usr/share/nginx/html
              subPath: volumes/pam-client-static-files
      volumes:
        - name: code-base
          persistentVolumeClaim:
            claimName: code-base
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pam-client
    app.kubernetes.io/part-of: excalibur-v4-dev
  name: pam-client
spec:
  ports:
    - name: node-inspector
      protocol: TCP
      port: 5858
      targetPort: 5858
    - name: tcp-3001
      protocol: TCP
      port: 3001
      targetPort: 3001
  selector:
    app: pam-client
    app.kubernetes.io/part-of: excalibur-v4-dev
    deployment: pam-client
