---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: '["database","loki"]'
    app.openshift.io/vcs-uri: 'https://github.com/excalibur-enterprise/excalibur-v4-api'
  labels:
    app: repository
    app.kubernetes.io/part-of: excalibur-v4-dev
  name: repository
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repository
      app.kubernetes.io/part-of: excalibur-v4-dev
      deployment: repository
  template:
    metadata:
      labels:
        app: repository
        app.kubernetes.io/part-of: excalibur-v4-dev
        deployment: repository
    spec:
      containers:
        - command: ['sh', '-c', 'cd /opt/excalibur/repository; npm run dev']
          env:
            - name: DEV_MODE
              value: 'true'
            - name: EXC_REPOSITORY_DB_HOST
              value: database
            - name: EXC_REPOSITORY_DB_USER
              value: root
            - name: EXC_REPOSITORY_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-root
                  key: password
            - name: EXC_REPOSITORY_LOG_CONSOLE_ENABLED
              value: 'true'
            - name: EXC_REPOSITORY_LOG_CONSOLE_LEVEL
              value: debug
            - name: EXC_REPOSITORY_LOG_LOKI_ENABLED
              value: 'false'
          # image: registry.access.redhat.com/ubi8/nodejs-20
          image: ghcr.io/excalibur-enterprise/repository:4.0.0-alpha.2
          name: repository
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
            initialDelaySeconds: 30
          resources:
            requests:
              cpu: 1m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: code-base
              mountPath: /opt/excalibur/repository
              subPath: excalibur-v4/services/repository
      imagePullSecrets:
        - name: ghcr-auth
      volumes:
        - name: code-base
          persistentVolumeClaim:
            claimName: code-base
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: repository
    app.kubernetes.io/part-of: excalibur-v4-dev
  name: repository
spec:
  ports:
    - name: node-inspector
      protocol: TCP
      port: 5858
      targetPort: 5858
    - name: grpc
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: repository
    app.kubernetes.io/part-of: excalibur-v4-dev
    deployment: repository
