---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: '[]'
    app.openshift.io/vcs-uri: 'https://github.com/excalibur-enterprise/excalibur-v4-api'
  labels:
    app: test-ssh-pass
    app.kubernetes.io/part-of: excalibur-v4-dev
  name: test-ssh-pass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-ssh-pass
      app.kubernetes.io/part-of: excalibur-v4-dev
      deployment: test-ssh-pass
  template:
    metadata:
      labels:
        app: test-ssh-pass
        app.kubernetes.io/part-of: excalibur-v4-dev
        deployment: test-ssh-pass
    spec:
      containers:
        - env:
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
            - name: TZ
              value: 'Etc/UTC'
            - name: SUDO_ACCESS
              value: 'false'
            - name: PASSWORD_ACCESS
              value: 'true'
            - name: USER_PASSWORD
              value: 'password'
            - name: USER_NAME
              value: 'excalibur'
          image: lscr.io/linuxserver/openssh-server:latest
          name: test-ssh-pass
          readinessProbe:
            tcpSocket:
              port: 22
            timeoutSeconds: 1
            initialDelaySeconds: 30
          ports:
            - containerPort: 22
              protocol: TCP
          resources:
            requests:
              cpu: 1m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-ssh-pass
    app.kubernetes.io/part-of: excalibur-v4-dev
  name: test-ssh-pass
spec:
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
  selector:
    app: test-ssh-pass
    app.kubernetes.io/part-of: excalibur-v4-dev
    deployment: test-ssh-pass
