---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: '[]'
    app.openshift.io/vcs-uri: 'https://github.com/excalibur-enterprise/excalibur-v4-api'
  labels:
    app: test-rdp
    app.kubernetes.io/part-of: excalibur-v4-dev
  name: test-rdp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-rdp
      app.kubernetes.io/part-of: excalibur-v4-dev
      deployment: test-rdp
  template:
    metadata:
      labels:
        app: test-rdp
        app.kubernetes.io/part-of: excalibur-v4-dev
        deployment: test-rdp
    spec:
      containers:
        - env:
            - name: GUEST_PASS
              value: 'excalibur'
          image: satishweb/xrdp:latest
          name: test-rdp
          ports:
            - containerPort: 3389
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 1
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-rdp
    app.kubernetes.io/part-of: excalibur-v4-dev
  name: test-rdp
spec:
  ports:
    - name: rdp
      protocol: TCP
      port: 3389
      targetPort: 3389
  selector:
    app: test-rdp
    app.kubernetes.io/part-of: excalibur-v4-dev
    deployment: test-rdp
