apiVersion: v1
items:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      labels:
        app: app-1
        app.kubernetes.io/part-of: loadbalancing-test
      name: app-1
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      labels:
        app: app-1
        app.kubernetes.io/part-of: loadbalancing-test
      name: app-1
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: app-1:latest
      source:
        contextDir: /
        git:
          uri: https://github.com/JurajBrabec/loadbalancing-test.git
        type: Git
      strategy:
        dockerStrategy:
          dockerfilePath: Dockerfile-app-1
        type: Docker
      triggers:
        - type: ConfigChange
        - type: ImageChange
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"app-1:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"app-1\")].image"}]'
      labels:
        app: app-1
        app.kubernetes.io/part-of: loadbalancing-test
      name: app-1
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: app-1
          app.kubernetes.io/part-of: loadbalancing-test
          deployment: app-1
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: 'true'
          labels:
            app: app-1
            app.kubernetes.io/part-of: loadbalancing-test
            deployment: app-1
            version: dev
        spec:
          containers:
            - env:
                - name: APP_2_ADDR
                  value: 'app-2:8080'
              image: 'image-registry.openshift-image-registry.svc:5000/loadbalancing-test/app-1'
              name: app-1
              ports:
                - containerPort: 8000
                  protocol: TCP
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: app-1
        app.kubernetes.io/part-of: loadbalancing-test
      name: app-1
    spec:
      ports:
        - name: tcp-8000
          port: 8000
          protocol: TCP
          targetPort: 8000
      selector:
        app: app-1
        app.kubernetes.io/part-of: loadbalancing-test
        deployment: app-1
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: app-1
        app.kubernetes.io/part-of: loadbalancing-test
      name: app-1
    spec:
      to:
        kind: Service
        name: app-1
      port:
        targetPort: tcp-8000
kind: List
