---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-2
  name: app-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-2
  template:
    metadata:
      labels:
        app: app-2
    spec:
      containers:
        - image: 'ghcr.io/jurajbrabec/loadbalancing-test/app-2'
          name: app-2
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-2
  name: app-2
spec:
  ports:
    - name: tcp-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: app-2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-2
  name: app-2-headless
spec:
  clusterIP: None
  ports:
    - name: tcp-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
  selector:
    app: app-2
