---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-2
    app.kubernetes.io/part-of: loadbalancing-test
  name: app-2-headless
spec:
  clusterIP: None
  ports:
    - name: tcp-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
  selector:
    app: app-2
    app.kubernetes.io/part-of: loadbalancing-test
    deployment: app-2
