---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: dev-image
    app.kubernetes.io/part-of: excalibur-v4-dev
  name: dev-image
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'dev-image:latest'
  successfulBuildsHistoryLimit: 1
  failedBuildsHistoryLimit: 1
  source:
    contextDir: /dev-image
    git:
      uri: 'https://github.com/JurajBrabec/loadbalancing-test.git'
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  triggers:
    - type: ConfigChange
    - type: ImageChange
