---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-uri: 'https://github.com/excalibur-enterprise/excalibur-v4'
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"dev-image:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"dev-image\")].image"}]'
  name: dev-image
  labels:
    app: dev-image
    app.kubernetes.io/part-of: excalibur-v4-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-image
      app.kubernetes.io/part-of: excalibur-v4-dev
      deployment: dev-image
  template:
    metadata:
      labels:
        app: dev-image
        app.kubernetes.io/part-of: excalibur-v4-dev
        deployment: dev-image
    spec:
      containers:
        - env:
            - name: GITHUB_PAT
              valueFrom:
                secretKeyRef:
                  name: github-pat
                  key: token
          envFrom:
            - configMapRef:
                name: environment-variables
          image: ' '
          imagePullPolicy: Always
          name: dev-image
          resources:
            requests:
              cpu: 1m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 3Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ['ALL']
            runAsNonRoot: true
            runAsUser: 1000710000
            seccompProfile:
              type: 'RuntimeDefault'
            supplementalGroups: [0, 1000710000]
          volumeMounts:
            - name: code-base
              mountPath: /opt/code-base
            - name: npmrc
              mountPath: /home/node/.npmrc
              subPath: .npmrc
      volumes:
        - name: code-base
          persistentVolumeClaim:
            claimName: code-base
        - name: npmrc
          configMap:
            name: npmrc
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - dev-image
        from:
          kind: ImageStreamTag
          name: 'dev-image:latest'
    - type: ConfigChange
